### ISSUE TITLE
dotnet maui support

### ISSUE THREAD

**Issue by Diaapi** [legistek/Xamarin.Forms.Platforms.Blazor#4]
I was reviewing your experiment and it is incredible. I don't know if you have done this but in Maui, but why don't you migrate this to dotnet Maui so we can help it have support since we know that Microsoft will only have support for Android, iOS, Windows and Mac in Maui. Can we, the community, implement web support? What do you think?

**Comment by legistek** [comment]
That's very kind thank you. I don't have a business use for MAUI at the moment as we made ourselves a proprietary framework that uses React JSX for the frontend markup and a Mono Webassembly (C#) view model backend. So we ultimately took quite a different approach from MAUI or Xamarin Forms.

But I published this anyway hoping Microsoft would take the cue and realize how eminently possible and useful this would be. But alas, for what surely must be business reasons they have decided that they do not want to extend MAU to the web or officially support any kind of "write once run anywhere" framework that includes the web.

However anyone is welcome to fork this and adapt it for MAUI and I would be delighted to see that happen.
